### ISSUE TITLE
More adjustments from client

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-cenpac#10]
1.  I wanted the “About Us” to be a little smaller.  The size overpowers the Cenpac logo Image above it.

2.  Put my phone number next to “Gallery” tab at the top.  I want it to be just be a phone number (no phone icon or “call us”)

3.  Right now, I only have Facebook, YouTube and Google+ for my social media.  (the links are below if your interested)

https://www.facebook.com/cenpacimages

https://www.youtube.com/channel/UCIQByUqcXYYtmUJtszsMQnA

https://plus.google.com/u/0/b/117170693641225206131/117170693641225206131/about

*My edits*
- Since Ken wants the phone number up top, remove the social media icons from the top menu, otherwise it won't all fit

due:
10-5-15   6p

**Comment by vanderbeam** [comment]
@rodneystrong I dropped the titles down from 55px to 45px already. I'm afraid dropping them down to even 35px give the rest of the titles no presence at all. I'm thinking of figuring out how to just take out the "ABOUT US" and the subtitle all together so it doesn't impact the rest of the section headers. How do you feel about that?

**Comment by vanderbeam** [comment]
@rodneystrong I'm going to need more time for this. I'm having trouble with the php. I'd also still like your input on the above comment.

**Comment by vanderbeam** [comment]
And I need the address and email address so I can put them in the footer.

**Comment by vanderbeam** [comment]
I'm going to look at this with a fresh pair of eyes tomorrow. Pretty much everything is done except adding the phone number. I'm working on trying to target the element (none of the usually targeting has worked). I also went ahead and took out the ABOUT US and subtitle so you could see how it looks.

**Comment by rodneystrong** [comment]
I emailed the client to check it out; I think you made a good choice in removing "About Us". 

I'll let you know if the client responds with his address.
