### ISSUE TITLE
Multiple new changes

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-cenpac#12]
Here's a screencast of them all:
http://somup.com/co6i3BbNO

Here's the content you'll need to copy/paste as mentioned in the video:

2491 Alluvial Ave  suite 22  Clovis, CA  93611        (559) 387-4150

Here's a link to the google doc for the rest of the content: 
https://drive.google.com/file/d/0B88_mCI0OTGkdk15SGxLMWY0bGM/view?usp=sharing

due:
10-9-15  4p

**Comment by jperez4509** [comment]
Done.
