### ISSUE TITLE
Replace "About Us" link at top with "Our Services"

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-cenpac#13]
like the title states

due:
10-9-15  3p

**Comment by jperez4509** [comment]
Done

**Comment by rodneystrong** [comment]
Sorry, I wasn't comprehensive in what else I needed done with this. 

Could you also make sure the "Our Services" links to the "Our services" section similar in behavior as the other links please?

**Comment by jperez4509** [comment]
Done
