### ISSUE TITLE
Create a logo for Cenpac Images

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-cenpac#2]
Cenpac Images is a business that uses drones to take aerial photos, whether it be for a business that wants a landscape photo of their tall building or a wedding couple that wants a high shot of their whole wedding, this business uses quadcopter drones to take aerial photos. 

for the logo: would like a clean simple modern style to it, 
dont want one of those *bam* hit you in the face logos. stick 
to simplicity but still convey a drone-flying business. would 
like the words 'cenpac images' in the logo itself as well.

My advice is to research the competitive landscape (look at other businesses that do the same stuff) and see what their logos look like and if you want to take that same route. 

Again, I want all three of you to work on this. If the way you did it last time worked well for you all then I encourage you to do it the same way again. If you want to try a little different method then I support that as well. 

due: 
9-5-15    8p

**Comment by jperez4509** [comment]
Does this business have a facebook account or a current website?

**Comment by rodneystrong** [comment]
Unfortunately no, and no  :(

**Comment by jperez4509** [comment]
I have uploaded the logo's and the style sheet to the google drive.
https://drive.google.com/folderview?id=0B8EN2ZGYf3v5YktLUkpXVjVVeVk&usp=sharing

**Comment by rodneystrong** [comment]
@jperez4509 @vanderbeam @AaronAguilar  just a reminder that all style guides are due 9p tonight. Have them fixed and uploaded onto the buildicus google drive folder please!  thanks

**Comment by jperez4509** [comment]
I have uploaded it to the google drive

**Comment by vanderbeam** [comment]
Ditto.

**Comment by AaronAguilar** [comment]
Link to the Google drive --
https://drive.google.com/folderview?id=0B8EN2ZGYf3v5YktLUkpXVjVVeVk&usp=sharing

**Comment by rodneystrong** [comment]
Good job everyone, thanks for putting in the effort. Glad everyone got their submissions on time as well. 

I've set up a meeting with the client this friday (tomorrow) at 1p to present these.
