### ISSUE TITLE
"Our Services" section update

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-cenpac#20]
Change the following section.  Put each service on a separate line (not separated by 

comas)

Our Services

Real Estate: Industrial: Sports and Events

Residential Bridge Inspection Golf Courses

Construction Reservoir Inspection Sports Events

Hotel/Resort Canal Inspection Weddings

Grand opening Insurance Claims Charity Events

Here's exactly how it's supposed to be formatted/layed out: 

<img width="624" alt="screen shot 2015-10-14 at 5 49 30 pm" src="https://cloud.githubusercontent.com/assets/539962/10501997/079903c0-729c-11e5-9c71-b7b5ac76061c.png">

due:
10-16-15   10p

**Comment by vanderbeam** [comment]
Oops! I finished this yesterday sorry, it's done.

**Comment by rodneystrong** [comment]
thaaaank you miss
