### ISSUE TITLE
Issues client found

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-cenpac#24]
>1. When I click on the info@cenpacimages.com, it shows the address as ken@cenpacimages.com

>2. When I click on the “Clovis, CA” address at the bottom, it shows my alluvial address.  Don’t really mind but if we can get rid of the “suite22” part than that would be ok.

For the address, just get rid of it and only use Clovis, CA

due:
10-22-15  11p

**Comment by vanderbeam** [comment]
Ah this made me feel stupid. OK fixed it.

**Comment by rodneystrong** [comment]
good work dude

**Comment by rodneystrong** [comment]
shit happens, just be sure you continue to try to pay close attention to detail.
