### ISSUE TITLE
More changes from the client (again)

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-cenpac#25]
>Hi Alex.  Went through the site with my wife and here are a few small changes.

1. Under Laurleen profile”...Laurleen understands the DESIRES and demands of clients…..”  Replace the word needs with desires.  Under Ken profile”….capturing those amazing shots that will bring your project to life.  He will work closely with you to ensure….”  Just need to break up this long sentence by adding the period.

2. “Our Services” - “Real Estate” - eliminate the space at the top and a period at the end of the sentence for “grand openings.”

3. “Pricing”  “Aerial Video Packages” “Basic”  Need a “)” at the end of the $50 commercial license fee.

4.  Laurleen hates her picture.  Sorry about that…have you ever met a woman who loved their picture:)  As a quick fix, can you zoom out a little for both pictures.  Her long term fix is to give our pictures to her friend and have her photoshop us a little and then send it back to you.  

Still nothing on the email but the site looks great.    

due:
10-22-15   11p

**Comment by vanderbeam** [comment]
All set except for one thing....

```“Our Services” - “Real Estate” - eliminate the space at the top and a period at the end of the sentence for “grand openings.”```

What space at the top?

**Comment by rodneystrong** [comment]
Not exactly sure.. I'll touch base with client tomorrow.

**Comment by rodneystrong** [comment]
everything looks good though. thanks for the effort

**Comment by rodneystrong** [comment]
Found out what the issue is. It's a cross-browser issue that I assigned to Aaron since he's got a Mac with Safari. #27
