### ISSUE TITLE
replace the pictures

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-cenpac#26]
>Alex, can you please replace the photos with the ones I've attached.  They are the same photos with the same labels but with 2 differences.  I touched them up so they look better and I tried to make them all the same size so they look better when laid out on the website and when they are opened.  (I left out "Canal inspection")

I'll send the email with all the photo links

due:
10-28-15   4p

**Comment by vanderbeam** [comment]
Done

**Comment by rodneystrong** [comment]
Oh crap, I forgot to tell you, we launched the site!!  

The live url is cenpacimages.com  

So you'll need to do this again on the live site at cenpacimages.com/wp-admin with your same credentials. 

**So sorry!**  >.<)

**Comment by rodneystrong** [comment]
Please remember to replace the photos on the individual "Our Services" category pages as well.
http://cenpacimages.com/real-estate/
http://cenpacimages.com/industrial/
http://cenpacimages.com/events-and-sports/

with the new images you put into the Gallery page.

**Comment by vanderbeam** [comment]
All set

**Comment by rodneystrong** [comment]
ty ty
