### ISSUE TITLE
more edits from client

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-cenpac#29]
>Hi Alex.  I realized that I’ve been sending I’ve been sending emails here and there about small changes to the site.  Thought it might be easier if I just summarized the list in in one email:

1.  Replace existing drone pictures with the new enhanced ones.

2.  Adjust video page so the title is centered and videos are (slightly) smaller thumbnail that opens the video to the size it is currently.

3.  Replace front page Yosemite picture with the original trying to keep waterfall and half dome in the image.  Use it for the bottom picture also.  Let me know it I need to buy it first.

4.  Add the word “drone” in the following sentence and get rid of unmanned aerial vehicles.   I want to have the word drone on my site so google will find it in its search.  
…. and we  are approved by the FAA to operate drones for commercial purposes and….. we carry complete liability insurance.

5.  Add the sentence “We serve Fresno and the entire Central Valley” just above the FAA logo (and below my business description).  I’m also trying to make sure my site has the word Fresno and Central Valley so google will pick it up in a search.

Please call if you have questions.  I might be working but I’ll return your call as quick as I can.  Also, thanks for fixing the “Get in Touch” issue.  Works great now

due:
10-31-15    3p

**Comment by rodneystrong** [comment]
fyi  you already did # 1 in that list

# 3 will be tricky. finish the other items and then ping me for # 3

**Comment by rodneystrong** [comment]
Here's some more explanation: 

so # 3 I was going to try and figure out on my own but I dont have time

aleeex [12:19 PM]
i'll put it on you. here's the deal about it. It's a photoshopped image of an original that is found on the 500px website

aleeex [12:19 PM]
i think you found it not too long ago when i sent you on that hunt

aleeex [12:20 PM]12:20
but the original has a grey mountain, not a brown mountain. the one we have has been clearly altered. not only do we want to be able to use the original for commercial purposes, but also to be able to ALTER the original and use the ALTERED image for commercial purposes

aleeex [12:21 PM]
you'll need to contact the original author and ask if he/she allows the photo to be altered and used commercially. if the author needs more clarity on alternation, send a direct link to the image with the brown mountain.

aleeex [12:21 PM]
clear?

aleeex [12:22 PM]
For # 2

aleeex [12:23 PM]
He wants a plugin that allows us to resize the video thumbnails to be larger than the image thumbnails, but just like how when you click on the image thumbnails a modal window pops up of a larger image, same thing for the video thumbnails; a larger modal window pops up of a larger video.

aleeex [12:23 PM]
let me know when you've read and understood this. i'd be happy to get on a call to clarify further

**Comment by rodneystrong** [comment]
What's the word from the author about using that image?

**Comment by vanderbeam** [comment]
We are allowed to alter it however we wish, so that's not the issue at all. 

However, I was browsing the licensing agreement and it states ". Licensee may not without obtaining specific written consent (which may not be available): Falsely represent, expressly or impliedly, that Licensee is the original creator of a visual work that derives a substantial part of its artistic components from the Images." 

I feel we fall into a grey area wherein we're not telling people that Ken took this photo, I think people generally assume any photographs on a photographer's website were taken by said photographer. Do you think that would be an issue?

**Comment by rodneystrong** [comment]
This is good info. Let me touch base with Ken about this.
