### ISSUE TITLE
Design inspiration for site

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-cenpac#3]
Straight from the client: 
"Alex, here is another website that I really like.  I especially like the top bar options, the buttons that lead to videos and the quotation button (except it needs a field that offers a description of the desired service).  I don’t care for their logo but I like the simple and clean design of the website."

due:
9-9-15   5p

**Comment by vanderbeam** [comment]
@rodneystrong Was there suppose to be a link or a photo attached to this?

**Comment by rodneystrong** [comment]
http://www.topganservices.com

my bad
