### ISSUE TITLE
Learn how to install WP from scratch

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-cenpac#30]
go to cenpac-test.editllc.com and finish the wordpress install. 

install the MP stacks plugin and use the knapstack theme.

recreate the cenpacimages.com website with this theme. 

take notes on the good and bad parts about using MP Stacks and separate notes about the Knapstack theme

due:
11-9-15    5p

**Comment by rampage1213** [comment]
Getting used to MP Stacks updating due date: 11-9-15 11p

**Comment by rampage1213** [comment]
really close to being done ran into some problems will done tomorrow

**Comment by rampage1213** [comment]
Playing around with page builder and MP Stacks there are some pros and cons one plugin might be good for one site design as the other might work better on a different design the first big thing is that on MP stacks you can only have one text one image, one video one image ect.. but never 2 text, 2images ect... However you can do 3 text boxes on the left and a image on the right but when compared to page builder you can have many rows and pick what's in each row. On the other hand with page builder putting a background color/background Image on to a row is trickier than compared to MP Stacks where I can just have a background color/background Image for every row that is made. These are just something I have found, will post about more when found.
