### ISSUE TITLE
Change hero image

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-cenpac#31]
Ken got back with some photos he likes:

http://depositphotos.com/search/yosemite-waterfalls-st540.html?qview=35700937&4v7yz8

http://depositphotos.com/search/yosemite-waterfalls-st540.html?qview=22341509&4v7yz8
(he likes this one the most)

http://depositphotos.com/search/yosemite-waterfalls.html?qview=5011219&4v7yz8

http://depositphotos.com/search/yosemite-waterfalls-st120.html?qview=5274830&4v7yz8

http://depositphotos.com/search/half-dome-sunset.html?qview=29006445

http://depositphotos.com/search/half-dome-sunset.html?qview=26708787

Photoshop all 6 of these and screenshot them with the logo on them and then upload them here.

due:
11-11-15   10a

updated due:
12-1-15     5p

updated due:
12-5-15  3p

updated due:
12-16-15  3p

updated due:
12-26-15    4p

**Comment by vanderbeam** [comment]
@rodneystrong I have to agree with Ken. I think as far as perspective goes it fits the best as far as getting a portion of the falls and half dome into the narrow space. Some of these are INCREDIBLY pixalated so you make need to zoom out to get a proper idea. My votes go to 4 and 6. 

![6](https://cloud.githubusercontent.com/assets/12962001/11086801/7f43aa88-8809-11e5-8a40-6c675f039f7b.png)
![1](https://cloud.githubusercontent.com/assets/12962001/11086800/7f437d6a-8809-11e5-8b91-baf925b97145.png)
![2](https://cloud.githubusercontent.com/assets/12962001/11086802/7f4620ec-8809-11e5-91e0-c6f22d47fc80.png)
![3](https://cloud.githubusercontent.com/assets/12962001/11086803/7f48d21a-8809-11e5-81e3-957cb3d7f321.png)
![4](https://cloud.githubusercontent.com/assets/12962001/11086804/7f4a9dca-8809-11e5-8ed3-8098ba18c9c6.png)
![5](https://cloud.githubusercontent.com/assets/12962001/11086805/7f4ae10e-8809-11e5-8e88-d1c6e88ac521.png)

And as much as I adore that beautiful background on the contact area I wasn't sure if he was also interested in replacing that one so I threw his favourite photo in the contact us background and also the one I thought looked best down there. 

![4-contact](https://cloud.githubusercontent.com/assets/12962001/11086842/e7248686-8809-11e5-996e-c56c1d6600ae.png)
![9-contact](https://cloud.githubusercontent.com/assets/12962001/11086841/e72460d4-8809-11e5-9127-0cf0a6e781ac.png)

**Comment by rodneystrong** [comment]
Good job with these dude. Client came back and wants to see higher-res versions of Op-1 and Op-3. Do me a favor, go to this folder and find Op-1 and Op-3, purchase the high-res versions, and then recreate them with the high-res versions and then repost them here please. 

https://drive.google.com/open?id=0B88_mCI0OTGkNjJjdXh3NW9GRTA

**Comment by vanderbeam** [comment]
These are uploaded. HERO_1/2

**Comment by rodneystrong** [comment]
perfect, thank you!

**Comment by rodneystrong** [comment]
Ok, got another iteration ready. I manipulated the vibrance and clarity on Op-1 and Op-3 and uploaded them to the google drive. They should be titled yose-1 and yose-2 in the "hero images" folder. Please use them to recreate what you did with Op-1 and Op-3 please.

due:
12-1-15   5p

**Comment by vanderbeam** [comment]
Yose 1: https://drive.google.com/file/d/0B7-L_YWYH3_YRkZnbDVGRlJIeUE/view?usp=sharing
Yose 2: https://drive.google.com/file/d/0B7-L_YWYH3_YY0pQSlpVcnVUUlE/view?usp=sharing

**Comment by vanderbeam** [comment]
Oops it just occurred to me I need to screenshot the site. one minute.

**Comment by vanderbeam** [comment]
![2](https://cloud.githubusercontent.com/assets/12962001/11518925/67f1fc8a-984a-11e5-956d-14c86f9ec90d.jpg)
![1](https://cloud.githubusercontent.com/assets/12962001/11518924/67f0728e-984a-11e5-991a-10e0d8c1db3a.png)

**Comment by rodneystrong** [comment]
He wants the 1st image, but it looks too pixelated. Please recreate the 1st one but make sure the positioning and clarity is the same as you did it before here: https://drive.google.com/open?id=0B7-L_YWYH3_YWHE2WmJsZGFIaDQ


due:
12-3-15    6p

**Comment by rodneystrong** [comment]
*poke poke*

**Comment by vanderbeam** [comment]
Position is no problem, but I'm not sure how I would go about getting the clarity better. It was only better before because it was the HD picture from downloading it rather than using the low definition filler copy with the watermarks.

**Comment by vanderbeam** [comment]
It's still not great. 

![hero](https://cloud.githubusercontent.com/assets/12962001/11603999/1746ae1c-9a9c-11e5-9012-45e95f159c93.jpg)

**Comment by rodneystrong** [comment]
I like it much better than the previous one. Please upload this to the site and screenshot it the way you did in the previous comments here and paste that screenshot here as well. 

due:
12-5-15   3p

**Comment by vanderbeam** [comment]
![hero](https://cloud.githubusercontent.com/assets/12962001/11652889/2975beba-9d4f-11e5-889d-4f19f38ee736.png)

All set: http://cenpacimages.com/

**Comment by rodneystrong** [comment]
Perfect, thanks for this. Well done. Just emailed the client. Let's hope he approves.

**Comment by rodneystrong** [comment]
Ok, client came back. Likes enhanced image but wants more of half-dome and the waterfall to be showing. I screwed up. 
So please redo this with the *position* of the image similar if not exactly like the one you did here: https://cloud.githubusercontent.com/assets/12962001/11086802/7f4620ec-8809-11e5-91e0-c6f22d47fc80.png

Again, use the same background image in the previous comment, but position it the same way you did in the link I posted in this comment. 

Also, put more of a drop-shadow/black background-blur on the logo itself so it's not lost into the background image. 

due:
12-16-15   3p

**Comment by rodneystrong** [comment]
@jperez4509  could you handle this please? The assets you need are in the drive folder. The instructions you need to follow are in the previous 5 or so comments. 

updated due:
12-26-15    4p

**Comment by jperez4509** [comment]
@rodneystrong I will work on this.

**Comment by rodneystrong** [comment]
Got reminded by Todoist about this. Just following up. If possible, by 2pm tomorrow, please put a date/time you can finish this by.

**Comment by jperez4509** [comment]
Done.
<img width="1655" alt="screen shot 2015-12-26 at 7 57 36 pm" src="https://cloud.githubusercontent.com/assets/8659273/12008788/14ac6e5a-ac0b-11e5-93f6-6e0af653c82c.png">

**Comment by rodneystrong** [comment]
Good job on this Joel. However, I just clocked the load time on the image and it's at a heavy 1.5MB. Could you do me a favor please and use photoshop to optimize the size of that image for web? Try to get it under 500kb while still maintaining the sharpness and clarity. If you're ambitious, try to go under 200kb. Just remember that the image still has to be visually sharp. 

due:
12-28-15   5p

**Comment by jperez4509** [comment]
DONE.
