### ISSUE TITLE
Change videos

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-cenpac#32]
Please Delete the 2 on there now and replace with these:

River Parkway Event Center
https://vimeo.com/145229053

River Parkway Fresno
https://vimeo.com/145229052

Doerksen Ranch
https://vimeo.com/145229050

B&B Ranch
https://vimeo.com/145230399

due
11-11-15   12p

**Comment by vanderbeam** [comment]
This is done.

**Comment by rodneystrong** [comment]
Nice job, I like how you did the layout for the vids
