### ISSUE TITLE
Feedback from client

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-cenpac#34]
>Assuming we can figure out how to use this picture given what I said in #1, the logo and the letter “cen” in cenpac kind of blend with the background.  It actually strains my eyes to look at it for any length of time. (I never felt that way with the old picture).  The “pac” and “images look good because they are located over a dark background.  I would like to figure out how to make my logo and name “pop” a little more and I think the only way to do it is to place it over a background where it won’t blend in.  And if that isn’t enough to ask for, I would like to do all this and have the picture still display a Yosemite theme of a waterfall or half dome.  

>I don’t mean to be so picky but I know first impressions are important and I really want this to make a good impression.  I know I’m super critical when I look at websites.  I feel I can learn a lot about the business just by looking at the quality of their website.  Please call me if you have any questions or concerns.

My guess is that you should make the cenpac logo a little larger, put in a darker dropshadow/outer glow on it, and make sure you're still not covering up Half Dome circled in red here: 

![screen shot 2015-12-28 at 6 46 41 pm](https://cloud.githubusercontent.com/assets/539962/12028878/8d04ed9e-ad93-11e5-9913-2469cd8510eb.png)

due:
12-29-15   2p

updated due:
1-12-16  3p

**Comment by rodneystrong** [comment]
More feedback from client: 

>Logo looks good.  Picture looks way better but would like to see if it can sharpened up just a bit more (if that’s possible).  

>Do you have a different picture you can put behind the “Get in Touch?”  The quality of the picture and the actual picture look good but there's something about the orange background that doesn’t seem very appealing.  I would actually like that picture if the mountain wasn’t orange.  

>Thanks for your work.  Hope you have a happy New Years.

**Comment by jperez4509** [comment]
I updated the hero image and the background image in "Get In Touch". I removed and edited the image using Lightroom and Photoshop. Below is the updated image:

![site-used-2](https://cloud.githubusercontent.com/assets/8659273/12042877/35a72818-ae34-11e5-888d-e9861eba5766.jpg)

**Comment by rodneystrong** [comment]
Feedback from client: 
>I like the drop shadow and the lower image looks much better.  I still wish we could get a sharper picture on the top but I understand what your saying.  What would we have to do to get a picture (similar to whats on there) that has better resolution?  Could I pay for a picture that is better quality?  I’m open to suggestions.  Thanks.
Ken Lake

Could you go to depositphotos and find an image that's similar to the current hero image? Don't worry too much if it's not as colorful, I'll pull it into lightroom and make the adjustments. 

due:
1-5-16  3p

**Comment by jperez4509** [comment]
option 1: http://depositphotos.com/35699637/stock-photo-yosemite-el-capitan-and-half.html
![image](https://cloud.githubusercontent.com/assets/8659273/12110336/15db7aa0-b340-11e5-947c-9fe7f0d0005d.png)

option 2: http://depositphotos.com/38721995/stock-photo-yosemite-waterfall.html
![image](https://cloud.githubusercontent.com/assets/8659273/12110356/32e9d2ea-b340-11e5-8d15-894ca5aad4da.png)

option 3: http://depositphotos.com/9571507/stock-photo-yosemite.html
![image](https://cloud.githubusercontent.com/assets/8659273/12110362/42f47fa0-b340-11e5-995c-ed5579d118cb.png)

**Comment by rodneystrong** [comment]
@jperez4509 I was initially going to use the second image you posted, but then noticed another image in their suggestions that I just had to go for. I already photoshopped and cropped it, all I need you to do is add your logo with the same amount of drop-shadow as before. Try to position the logo to be over the sky and to the right of "el capitan". https://drive.google.com/open?id=0B88_mCI0OTGkbzVMTk1wSG9pTGc

That's a PNG file, but when you're done, you'll need to export as a JPG (remember to keep it under 500kb). 

Crop it to get the right effect/aspect ratio as necessary. 

due:
1-6-16   2p

**Comment by jperez4509** [comment]
@rodneystrong I have completed this and updated the site.

![cenpac-hero9](https://cloud.githubusercontent.com/assets/8659273/12136758/c18fc2c4-b3ff-11e5-82ad-43b38b080728.jpg)

**Comment by rodneystrong** [comment]
Unfortunately, there's issues: 

<img width="1370" alt="screen shot 2016-01-11 at 5 59 23 pm" src="https://cloud.githubusercontent.com/assets/539962/12252551/171577ac-b88d-11e5-9c0a-52b842672c2f.png">

Please look at the screenshot and fix everything you see. 

Also, please visit the website cenpacimages.com and look at the top hero image. You may need to adjust your image to be less 'zoomed in' so the mountains don't start to look blurry. 

due:
1-12-16   3p

**Comment by jperez4509** [comment]
*UPDATE*: I am going to add an actual html tag to add the background image with El Capitan and the Cenpac logo to the front-page.php. This should make this section more responsive.

**Comment by rodneystrong** [comment]
i love it. do it.

**Comment by jperez4509** [comment]
@rodneystrong I have completed this! Done.
