### ISSUE TITLE
Find a WP template and install it

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-cenpac#4]
Do a search for a free template that matches closely with what you've coded based on our template. 

Some suggestions for search:
free wordpress bootstrap template
free single page wordpress bootstrap template
free one page wordpress bootstrap template

If the free search doesn't yield favorable results, search through themeforest.com

Once you find a theme, install it  on cenpac.editllc.com

due:
9-21-15   3p

**Comment by rodneystrong** [comment]
As requested, I am extending deadline to this Friday

**Comment by vanderbeam** [comment]
@rodneystrong UPDATE: I found a nice, similar template that I've been editing the css/php to meat the similar requirements: http://cenpac.editllc.com/

I'm going to replace that image with a slider, figure out how to replace the contact area to look closer to ours, add a section for pricing, and anchor the different sections (those are the big things I know there are some miscellaneous questions). Are these things acceptable?

QUESTIONS:
- The theme has a few places where they use green, orange, blue, and gold. Do you want me to keep those colours or change them to the blue I've been using? 
- Do you like the blog section? I couldn't recall if that was something the client wanted
- I really like the testimonials and team section in this theme. Do you want me to change them or do you prefer them also?

Let me know!

**Comment by rodneystrong** [comment]
Sure thing, go ahead, all you'll need to do is install and activate the new theme while keeping the old theme inactive, that way if we need to switch back it won't take long to do.

Does this push back your deadline?

**Comment by vanderbeam** [comment]
@rodneystrong It's coming along pretty timely (is the deadline 5pm friday?)
I asked a couple questions above I still need clarified when you have a moment.

**Comment by rodneystrong** [comment]
Yes, the deadline in the description says 5p friday. When in doubt, please check the description.

Sorry I didn't answer the specific questions:

1. change them to the blue
2. he doesn't want to blog, so remove it for now
3. when you say "change them", what do you mean? change them to what? or did you imply 'remove them' ?  keep the team section no matter what

**Comment by vanderbeam** [comment]
@rodneystrong I mean keep the styling of the testimonies and team sections as they appear in the theme, or change them to the styling I'd done in the original styling (http://editllc.github.io/client-cenpac/)

**Comment by rodneystrong** [comment]
Ah ok. I prefer the way you styled the team section, but let's go with the way the WP theme has it. Let's also use the theme's testimonials section.

**Comment by vanderbeam** [comment]
http://cenpac.editllc.com/

Gallery on a separate page
Pricing on a separate page 
The only thing I didn't quite figure out is how to incorporate the Google Map (without upgrading to the pro anyway). Is that an issue considering this business doesn't really have a location?

Usually we upload all our code to github... what's the protocol with a wordpress site?

**Comment by rodneystrong** [comment]
Great job Meg, here's a video critique I have that includes many of the changes I'd like you to make:
http://screencast-o-matic.com/watch/coQqeIf7oJ

Also, for the google map we may have to use a separate plugin; i'll also have to get an address from Ken.

When it comes to the WordPress site it's the same deal, we upload the code here. 
What I want you to do is make sure your gh-pages branch is up to date and then upload this WordPress code to the MASTER branch. I want to preserve your hand-coded version JUST IN CASE but make sure this time you DON'T keep the master and gh-pages branches in sync (like we do for other projects). 

I've updated the due date for this issue.

**Comment by vanderbeam** [comment]
http://cenpac.editllc.com/

I have a google maps plugin but it doesn't give me the option for it to be placed in the contact us section. I can create a new page?

**Comment by rodneystrong** [comment]
Do it and let's see how it looks. 

In the mean time, figure out a way to embed a google map the way you initially mocked it up.
