### ISSUE TITLE
Adjustments requested by client

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-cenpac#9]
1.  Can you insert the picture below into my background?  Looks similar to the other one but It might be a slightly sharper image. Try it out and see what you think.  I trust your opinion on this.
![img_3133](https://cloud.githubusercontent.com/assets/539962/10097287/eb559008-632c-11e5-9477-0281e995fa42.JPG)

2.  I’d like to make the social messaging icons a slight bit more noticeable,  So far I only have the 3 set up (at the bottom of this message). Put these at the top to the right of the menu, exactly the way it's done here: http://pumpkinsfresno.com/

3.  The gallery section can be broken down into 2 sections:  “videos” and “images"

4.  (This is my wife suggestions)  Somewhere near the top (maybe just below the image) I’d like to have my phone number.  She likes it when she can see a phone number on the front screen without having to scroll down or search for it. (559) 908-7701

5.  “What is Aerial Imaging” - Maybe put a photo of the drone here in addition to the video (you can use the one I sent you or you can probably find something better on the internet).  I can talk about the drone and what it does.  

6.  “Get in Touch” - I’d like a phone number to be displayed first and then have the email link.   559) 908-7701

7.  Maybe make the headings in the main body (About Us etc…) a bit smaller.  The “About Us” seems to overpower the Cenpac logo

due:
9-30-15  1p

**Comment by vanderbeam** [comment]
http://cenpac.editllc.com/

This is ready. I had to install another plugin for videos. I'm struggling with figuring out how to style it (though the default style isn't super off base). Let me know if that all looks alright.

**Comment by vanderbeam** [comment]
It looks like I may not be able t without buying the full plug-in. Check out that style on the video plug-in. If you don't like it I'll look for a different plug in. 
(The reason I'm not using the video one is because it has a 2mb maximum)

**Comment by rodneystrong** [comment]
What's the name of the plugin? 

What page is the styling I should be looking at on?

**Comment by vanderbeam** [comment]
The gallery: http://cenpac.editllc.com/gallery/

And the new plugin is called "Huge-IT Video Galleries"
